### PR TITLE
Switch to more conventional matplotlib import

### PR DESCRIPTION
**Pull request by eteq**
This PR makes the minor suggestion of changing the pyplot imports in the day3 bayes exercises to use `plt` as the short form of `pyplot` instead of  of `mp` - this is the traditional convention the matplotlib team generally recommends.

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
cc @sfeeney - could you please confirm you're OK with changing this?

**Comment by eteq** [comment]
(should have noted in the description that I did briefly chat with @sfeeney about this, but should also get confirmation here since he was busy actually *teaching* the tutorial at the time, of course!)

**Comment by bsipocz** [comment]
Oh, if he was looped in it already, I'm happy to hit merge any time.

**Comment by bsipocz** [comment]
Hmm, looking into the notebooks I would also suggest to change the scipy imports. Keeping the full spelling of the scipy and numpy imports would make the notebook more clear I think.

**Comment by sfeeney** [comment]
Hi all!

I'm happy to change whatever imports desired to maintain clarity. I just
used my standard shorthand as we were low on time :)

Cheers!

Stephen

**Comment by bsipocz** [comment]
Thanks both. I'm merging this now, but may open another PR for the other imports.

**Pull request merged**
